name: course
channels:
  - conda-forge
dependencies:
  - cmasher
  - jupyter
  - pandas
  - pillow
  - pyarrow
  - requests
  - scipy
  - seaborn
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - sphinx-togglebutton  
  - matplotlib
  - numpy
  - scikit-learn
  - linkify-it-py
  - pip
  - xgboost
  - pyreadstat  
  - termcolor
  - time  
  - panel
  - pip:
      - setuptools
      - lxml
      - adjustText
      - highlight-text
      - sphinxcontrib-youtube
      - myst-parser
      - ffmpeg  